### ISSUE TITLE
Communication between scene

### ISSUE THREAD

**Issue by anoop4real** [HelmMobile/clean-swift-templates#2]
Hi,

If one scene need to trigger a method in another scene how will you do? Say for example, I have a webviewcontroller which is used to display contents like books/ pages etc and I have a full clean swift cycle for it, and I have js functions written in the view controller which can be triggered. Now I have a container view and I need to load the out put of a js function to this container from the webviewcontroller scene.

ie scene 2-->Viewcontroller-->On Button Click-->Invoke-->Scene1-->WebviewController-->Evaluatejs-->getOutPut-->giveit to -->Scene 2-->Interactor

**Comment by Mijail** [comment]
Hi,

The data passing method we use is really generic. It is to try to cover the case when simple data is passed which we found we used a lot.

I wouldn't recommend it to use on a really specific cases like yours, where it is important to have a unique definition on the protocol and what it does. I would recommend using a delegate between both interactors or workers. We use that a lot when we pass data backwards, to have a clear definition on what it is happening and improve readability.

I would recommend you to use some kind of DI framework (or build your own) to set the delegates so if you ever test you can change it in an easy way but that is obviously optional.

Also I think that the "getOutput" should be handled by the Scene1 Interactor and then send it to its delegate on the interactor of scene2 so that communication could be done between both interactors instead of using the viewcontroller.

In any case as I understand this is not an issue with the templates but just a programmatic problem.
